INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (1, NULL, 'Aebi', 'Aebi', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (2, NULL, 'Aprilia', 'Aprilia', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (3, NULL, 'BMW', 'BMW', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (4, NULL, 'Bosch', 'Bosch', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (6, NULL, 'Citroen', 'Citroen', '1', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (7, NULL, 'Daewoo', 'Daewoo', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (8, NULL, 'DAF', 'DAF', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (9, NULL, 'Daihatsu', 'Daihatsu', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (10, NULL, 'Daimler-Chrysler', 'Daimler-Chrysler', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (11, NULL, 'ESA', 'ESA', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (12, NULL, 'Fiat/Alfa gültig bis 15.06.11', 'Fiat', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (14, NULL, 'Ford', 'Ford', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (15, NULL, 'Forrer', 'Forrer', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (16, NULL, 'FZR, Reussbühl', 'FZR', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (17, NULL, 'Gilera-Motos', 'Gilera-Motos', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (18, NULL, 'Harley-Davidson', 'Harley-Davidson', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (19, NULL, 'Heizmann', 'Heizmann', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (20, NULL, 'Hella Autozubehör', 'Hella', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (21, NULL, 'Honda Autos', 'Honda', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (22, NULL, 'Hostettler Auto A', 'Hostettler', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (23, NULL, 'Hostettler Auto E', 'Hostettler', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (24, NULL, 'Hostettler Auto W', 'Hostettler', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (25, NULL, 'Hostettler Auto Z', 'Hostettler', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (26, NULL, 'Hostettler Motorrad D', 'Hostettler', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (27, NULL, 'Hostettler Motorrad P', 'Hostettler', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (28, NULL, 'Hostettler Motorrad Z', 'Hostettler', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (29, NULL, 'Hyundai', 'Hyundai', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (30, NULL, 'Jaguar', 'Jaguar', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (31, NULL, 'Kawasaki', 'Kawasaki', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (32, NULL, 'KEW', 'KEW', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (33, NULL, 'Kia', 'Kia', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (34, NULL, 'MAN', 'MAN', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (35, NULL, 'Mazda', 'Mazda', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (36, NULL, 'Mazda Ersatz-Nummern', 'Mazda', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (37, NULL, 'Mitsubishi', 'Mitsubishi', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (38, NULL, 'Mohag K-Teile', 'Mohag', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (39, NULL, 'Nissan', 'Nissan', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (41, NULL, 'Opel Irmscher', 'Opel', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (42, NULL, 'Peugeot', 'Peugeot', '1', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (43, NULL, 'Peugeot (Franz)', 'Peugeot', '1', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (44, NULL, 'Piaggio Motos', 'Piaggio', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (45, NULL, 'Puch Motos', 'Puch', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (46, NULL, 'Rapid', 'Rapid', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (47, NULL, 'Renault', 'Renault', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (48, NULL, 'Rhiag Group Ltd.', 'Rhiag', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (49, NULL, 'Rover', 'Rover', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (50, NULL, 'Saab', 'Saab', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (51, NULL, 'Sahli', 'Sahli', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (52, NULL, 'Scania', 'Scania', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (53, NULL, 'SDF (Landmaschinen)', 'SDF', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (54, NULL, 'Seat', 'Seat', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (55, NULL, 'SMU Albiez Walter AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (56, NULL, 'SMU Alusuisse Allegra AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (57, NULL, 'SMU Debrunner AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (58, NULL, 'SMU Eberspächer AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (59, NULL, 'SMU Egger & Co AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (60, NULL, 'SMU Fischer & Cie AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (61, NULL, 'SMU Forster AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (62, NULL, 'SMU Glas Trösch AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (63, NULL, 'SMU H.Kohler AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (64, NULL, 'SMU Häuselmann AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (65, NULL, 'SMU Hans Saurer', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (66, NULL, 'SMU Hans Schmid AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (67, NULL, 'SMU Herrmann AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (68, NULL, 'SMU Jansen AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (69, NULL, 'SMU Kiener & Wittlin AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (70, NULL, 'SMU MTS Urdorf', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (71, NULL, 'SMU Pestalozzi AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (72, NULL, 'SMU Pilkington AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (73, NULL, 'SMU Saint-Gobain AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (74, NULL, 'SMU Schwarz Stahl AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (75, NULL, 'SMU SFS Unimarket AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (76, NULL, 'SMU Sprich AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (77, NULL, 'SMU Stahag AG', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (78, NULL, 'SMU Urs Meier Eurotrade', 'SMU', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (79, NULL, 'Subaru', 'Subaru', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (80, NULL, 'Suzuki Autos', 'Suzuki', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (81, NULL, 'Suzuki Motos', 'Suzuki', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (82, NULL, 'Technomag', 'Technomag', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (83, NULL, 'Toyota', 'Toyota', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (84, NULL, 'Triumph Motos', 'Triumph', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (86, NULL, 'Volvo', 'Volvo', '1', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (87, NULL, 'Wabco', 'Wabco', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (88, NULL, 'Yamaha', 'Yamaha', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (89, NULL, 'AMAG', 'Amag', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (90, NULL, 'Amsler Dolmar', 'Amsler', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (91, NULL, 'Bucher', 'Bucher', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (92, NULL, 'Chevrolet/Daewoo', 'chevrolet', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (93, NULL, 'Frankana', 'Frankana', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (94, NULL, 'Freiko', 'Freiko', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (95, NULL, 'Honda Motos', 'HondaMotos', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (96, NULL, 'IVECO', 'Iveco', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (97, NULL, 'Movera', 'Movera', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (99, NULL, 'Stihl / Viking', 'Stihl', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (101, NULL, 'Ducati', 'Ducati', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (102, NULL, 'Agrar', 'GVSAgrar', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (103, NULL, 'Krone', 'GVSAgrar', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (104, NULL, 'Rabe', 'GVSAgrar', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (106, NULL, 'Isuzu', 'Isuzu', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (108, NULL, 'Rüegg', 'Ruegg', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (109, NULL, 'AMAG RabCode Insert', 'AMAG', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (110, NULL, 'AMAG RabCode Update', 'AMAG', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (111, NULL, 'Kärcher', 'Kärcher', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (112, NULL, 'Suedo', 'Suedo', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (113, NULL, 'Ford Part DB', 'Ford Part DB', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (114, NULL, 'Reimo', 'Reimo', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (120, NULL, 'ClaasTraktor', 'ClaasCT', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (121, NULL, 'ClaasFilter', 'ClaasFilter', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (122, NULL, 'ClaasLandmachinen', 'ClaasCL', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (123, NULL, 'Hansa Flex', 'HansaFlex', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (129, NULL, 'Morini', 'Morini', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (130, NULL, 'Prillinger', 'Prillinger', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (131, NULL, 'Kverneland', 'Kverneland', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (132, NULL, 'Hoelzle', 'Hoelzle', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (133, NULL, 'Aupro', 'Aupro', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (134, NULL, 'Smart', 'Daimler-Chrysler', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (135, NULL, 'Suedo Text', 'Suedo', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (136, NULL, 'Kramp', 'Kramp', '0', '0', '0', NULL, NULL); 
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (137, NULL, 'Volvo_Pege', 'Volvo_Pege', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (138, NULL, 'Peugeot Motos', 'PeugeotMotos', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (142, NULL, 'Metabo', 'Metabo', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (143, NULL, 'Aupro_D1', 'Aupro', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (144, NULL, 'Aupro_D2', 'Aupro', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (145, NULL, 'Matra John Deere Merchandise', 'John Deere', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (146, NULL, 'Klaus-Häberlin AG B&S Motoren', 'Klaus-Haeberlin', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (147, NULL, 'Poettinger', 'Poettinger', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (148, NULL, 'Ochsner', 'Ochsner', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (150, NULL, 'Matra John Deere Landmaschinen', 'John Deere', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (151, NULL, 'Matra John Deere R&G', 'John Deere', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (153, NULL, 'Aixam', 'Aixam', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (154, NULL, 'Keller', 'Keller', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (155, NULL, 'Augros-Lumecor', 'Augros-Lumecor', '0', '0', '0', NULL, NULL);        
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (156, NULL, 'WSP Italy', 'WSP', '0', '0', '0', NULL, NULL);        
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (157, NULL, 'SsangYong', 'SsangYong', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (158, NULL, 'Fiat', 'Fiat', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (159, NULL, 'Fiat Abarth', 'Fiat', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (160, NULL, 'Fiat Alfa', 'Fiat', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (161, NULL, 'Fiat Rest', 'Fiat', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (162, NULL, 'Fiat Chrysler', 'Fiat', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (163, NULL, 'Fiat Jeep', 'Fiat', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (164, NULL, 'Fiat Lancia', 'Fiat', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (165, NULL, 'Maserati', 'Maserati', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (166, NULL, 'Granit', 'Granit', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (167, NULL, 'Matra John Deere Anbaugeräte', 'John Deere', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (168, NULL, 'Matra John Deere Zubehör', 'John Deere', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (169, NULL, 'Matra John Deere Zub.Werkstatt', 'John Deere', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (170, NULL, 'Matra John Deere Schmierstoffe', 'John Deere', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (171, NULL, 'Hostettler Motoren AG', 'Hostettler', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (172,  NULL, 'Aigner', 'Aigner', '0', '0', '0', NULL, NULL);             
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (173, NULL, 'Montagetechnik BERNER AG', 'Berner', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (174, NULL, 'Michelin/Kleber/BFGoodrich', 'Michelin', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (175, NULL, 'Klintberg & Way', 'Klintberg&Way', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (176, NULL, 'Pirelli/Ceat', 'Pirelli', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (177, NULL, 'Vredestein/Maloya', 'Vredestein', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (178, NULL, 'Goodyear/Dunlop/Fulda/Sava', 'Goodyear', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (179, NULL, 'Tam', 'Tam', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (180, NULL, 'Volvo Penta', 'VolvoPenta', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (181, NULL, 'Nissan Pege', 'Nissan-Pege', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (182, NULL, 'Lorch KG', 'Lorch', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (183, NULL, 'Apollo', 'Apollo', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (184, NULL, '.Manuell', 'Manuell', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (185, NULL, 'Bridgestone/Firestone', 'Bridgestone', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (186, NULL, 'Mercury MerCruiser', 'Mercury', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (187, NULL, 'Continental/Barum/Semperit/Uni', 'Continental', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (188, NULL, 'Dolmar', 'Dolmar', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (189, NULL, 'GM Opel', 'Opel', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (190, NULL, 'Ducati Parts', 'Ducati', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (191, NULL, 'Ducati Accessories', 'Ducati', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (192, NULL, 'Ducati Apparel', 'Ducati', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (193, NULL, 'Nokian', 'Nokian', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (194, NULL, 'Horsch', 'GVSAgrar', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (195, NULL, 'Kramer', 'GVSAgrar', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM) 
                 VALUES (196, NULL, 'John Deere', 'John Deere', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (197, NULL, 'Lindner', 'Lindner', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (198, NULL, 'Nissan GASS', 'Nissan', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (199, NULL, 'DFSK', 'DFSK', '0', '0', '0', NULL, NULL);
INSERT INTO MARKENDATEN (MAD_FNR, MAD_FKRDNR, MAD_FMARKE, MAD_FORDNER, MAD_FLEADZERO, MAD_FANPASSEN, MAD_FGKKORREKTUR, MAD_FDATATYPE, MAD_FDATUM)
                 VALUES (200, NULL, 'Infiniti', 'Infiniti', '0', '0', '0', NULL, NULL);				 
COMMIT WORK;