
/******************************************************************************/
/****         Generated by Any Tool 2009.06.15 21.10.2009 11:00:01         ****/
/******************************************************************************/

INSERT INTO EMPLOYEEPROFIL (EPR_FNR, EPR_FBEZEICH) VALUES (1, 'CHEF');
SET GENERATOR EPR_GNR TO 1;

COMMIT WORK;
